databases:
  - name: social
    databaseName: social
    user: social

services:
  - type: web
    name: social
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: social
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
