databases:
  - name: social
    databaseName: social
    user: social
    plan: free

services:
  - type: web
    name: social
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    # startCommand: "bundle exec puma -C config/puma.rb"
    # preDeployCommand: "./bin/rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "./bin/rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: social
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 #sensible default
